spring.application.name=backend

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/se2030}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:s3n4}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.jackson.serialization.fail-on-empty-beans=false
spring.jackson.default-property-inclusion=non_null

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://api.asgardeo.io/t/s3n4/oauth2/token
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://api.asgardeo.io/t/s3n4/oauth2/jwks

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG
logging.level.org.springframework.boot.autoconfigure.security=DEBUG

twilio.account.sid=
twilio.api.key=
twilio.api.secret=
twilio.phone.number=